apache/atlas

repository/src/main/java/org/apache/atlas/repository/store/graph/v1/HardDeleteHandlerV1.java
=> word wrong

addons/kafka-bridge/src/main/java/org/apache/atlas/kafka/bridge/KafkaBridge.java
This patch will fix spelling errors in kafka bridge.
=> ATLAS-4319 : Code refactoring in kafka bridge

pom.xml
changed pom.xml with email and org change updates
=> Changing email and organization for Barbara Stortz

intg/src/main/python/apache_atlas/client/entity.py
There was a typo in the remove_classification method where it was written formart instead of format
=> Update entity.py remove_classification method

client/client-v1/pom.xml, client/client-v1/src/main/java/org/apache/atlas/AtlasAdminClient.java, client/client-v1/src/main/java/org/apache/atlas/AtlasClient.java, client/client-v1/src/main/java/org/apache/atlas/CreateUpdateEntitiesResult.java, client/client-v1/src/main/java/org/apache/atlas/EntityAuditEvent.java, client/client-v1/src/test/java/org/apache/atlas/AtlasClientTest.java, client/client-v2/pom.xml, client/client-v2/src/main/java/org/apache/atlas/AtlasClientV2.java, client/client-v2/src/test/java/org/apache/atlas/AtlasClientV2Test.java, client/common/pom.xml, client/common/src/main/java/org/apache/atlas/AtlasBaseClient.java, client/common/src/main/java/org/apache/atlas/AtlasServerEnsemble.java, client/common/src/main/java/org/apache/atlas/AtlasServiceException.java, client/common/src/main/java/org/apache/atlas/ResourceCreator.java, client/common/src/main/java/org/apache/atlas/security/SecureClientUtils.java, client/pom.xml, dev-support/checkstyle-suppressions.xml
updated atlas-client modules for checkstyle compliance
build with tests complete successfully
=> ATLAS-4958: checkstyle compliance updates - atlas-client module

addons/couchbase-bridge/pom.xml, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/AtlasConfig.java, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/CBConfig.java, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/CouchbaseHook.java, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/entities/CouchbaseAtlasEntity.java, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/entities/CouchbaseBucket.java, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/entities/CouchbaseCluster.java, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/entities/CouchbaseCollection.java, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/entities/CouchbaseField.java, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/entities/CouchbaseFieldType.java, addons/couchbase-bridge/src/main/java/com/couchbase/atlas/connector/entities/CouchbaseScope.java, addons/couchbase-bridge/src/test/java/com/couchbase/atlas/connector/CouchbaseHookTest.java, addons/couchbase-bridge/src/test/java/com/couchbase/atlas/connector/entities/CouchbaseAtlasEntityTest.java
Updated `couchbase-bridge` module sources to comply with the check-style requirements.
`mvn clean verify` for the module on local machine.
=> ATLAS-4937: checkstyle compliance updates - couchbase-bridge module

dev-support/atlas-docker/Dockerfile.atlas-base
Add vim in docker base image
CI
=> ATLAS-4989: Add vim in docker base image

tools/atlas-index-repair/pom.xml, tools/atlas-index-repair/src/main/java/org/apache/atlas/tools/RepairIndex.java, tools/classification-updater/pom.xml, tools/classification-updater/src/main/java/org/apache/atlas/tools/BulkFetchAndUpdate.java, tools/notification-analyzer/pom.xml, tools/notification-analyzer/src/main/java/org/apache/atlas/tools/NotificationAnalyzer.java
Updated `tools` module sources to comply with the check-style requirements.
`mvn clean verify` for all sub-modules on local machine.
=> ATLAS-4968: checkstyle compliance updates - tools module

authorization/pom.xml, authorization/src/main/java/org/apache/atlas/authorize/AtlasAccessRequest.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasAdminAccessRequest.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasAuthorizationException.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasAuthorizationUtils.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasAuthorizer.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasAuthorizerFactory.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasEntityAccessRequest.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasNoneAuthorizer.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasPrivilege.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasRelationshipAccessRequest.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasSearchResultScrubRequest.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasTypeAccessRequest.java, authorization/src/main/java/org/apache/atlas/authorize/AtlasTypesDefFilterRequest.java, authorization/src/main/java/org/apache/atlas/authorize/simple/AtlasSimpleAuthorizer.java, authorization/src/main/java/org/apache/atlas/authorize/simple/AtlasSimpleAuthzPolicy.java, authorization/src/main/java/org/apache/atlas/authorize/simple/AtlasSimpleAuthzUpdateTool.java, authorization/src/test/java/org/apache/atlas/authorize/simple/AtlasSimpleAuthorizerTest.java
Updated authorization module for checkstyle compliance
Verified build with tests completed successfully.
=> ATLAS-4961: checkstyle compliance updates - atlas-authorization module

repository/src/main/java/org/apache/atlas/services/MetricsService.java, repository/src/test/java/org/apache/atlas/services/MetricsServiceTest.java, webapp/src/main/java/org/apache/atlas/web/resources/AdminResource.java
There is some information in the Metrics API response, which is not been used like Count of the typeAndSubTypes, Active, deleted, Shell. we have removed the count of details which are not used. Also we had kept the flag for backward compatibility.
Verified build with tests completed successfully.
=> ATLAS-4867 : Improve Metrics API

atlas-examples/pom.xml, atlas-examples/sample-app/src/main/java/org/apache/atlas/examples/sampleapp/DiscoveryExample.java, atlas-examples/sample-app/src/main/java/org/apache/atlas/examples/sampleapp/EntityExample.java, atlas-examples/sample-app/src/main/java/org/apache/atlas/examples/sampleapp/GlossaryExample.java, atlas-examples/sample-app/src/main/java/org/apache/atlas/examples/sampleapp/LineageExample.java, atlas-examples/sample-app/src/main/java/org/apache/atlas/examples/sampleapp/SampleApp.java, atlas-examples/sample-app/src/main/java/org/apache/atlas/examples/sampleapp/SampleAppConstants.java, atlas-examples/sample-app/src/main/java/org/apache/atlas/examples/sampleapp/TypeDefExample.java
…ements
Updated examples module sources to comply with the check-style requirements.
`mvn clean verify` for all sub-modules on local machine.
=> ATLAS-4962: atlas-example modules: update for code readability improvements

.github/workflows/ci.yml
=> ATLAS-4992: Increase CI job timeout

build-tools/src/main/resources/ui-dist/index.js
ATLAS-4998: Replaced Swagger Logo with Atlas Logo
manual tests
=> ATLAS-4998: Replaced Swagger Logo with Atlas Logo

.asf.yaml
Notifications should be present at the root level of .asf.yaml file.
Followed documentation here: https://github.com/apache/infrastructure-asfyaml/blob/main/README.md
=>  ATLAS-5004: Update notification settings in .asf.yaml

repository/src/main/java/org/apache/atlas/glossary/GlossaryService.java, repository/src/test/java/org/apache/atlas/glossary/GlossaryServiceTest.java
…ch - commit 92174bbd96bf61228a39b22a3c2b7a16b58cf95c
Check-style errors have been fixed
Manual  testing
=> ATLAS-4995: corrected checkstyle errors in the missing glossaries patch - commit 92174bbd96bf61228a39b22a3c2b7a16b58cf95c

pom.xml
Upgrade netty version to 4.1.118.Final
build completes successfully
=> ATLAS-5007: Upgrade netty version to 4.1.118.Final

pom.xml
Upgrade commons-io version to 2.17.0
build completes successfully
=> ATLAS-5009: Upgrade commons-io version to 2.17.0

docs/package.json
Upgrade axios version to 1.8.2+
build completes successfully
=> ATLAS-5010: Upgrade axios version to 1.8.2+

intg/src/main/java/org/apache/atlas/AtlasErrorCode.java, webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java, webapp/src/test/java/org/apache/atlas/web/integration/BasicSearchIT.java, webapp/src/test/resources/json/search-parameters/attribute-name.json, webapp/src/test/resources/json/search-parameters/attribute-value.json, webapp/src/test/resources/json/search-parameters/operator.json
Changes: Search Filter Validation and Test Cases written for attribute value, name and operator. Incorporated Data providers properly. 
unit tests, manual tests, API curl command testing done.
=> ATLAS-5005 : Basic search entity filter validation

docs/package-lock.json, docs/pom.xml
[ATLAS-5018](https://issues.apache.org/jira/browse/ATLAS-5018)
UI: Updating pom.xml & package-lock.json file in docs module
Manual test
=> ATLAS-5018: UI: Updating pom.xml & package-lock.json file in docs module

0001-ATLAS-5033-Migrate-Lineage-Module-from-Backbone.js-t.patch, dashboard/src/views/Administrator/AdministratorLayout.tsx, dashboard/src/views/Administrator/TypeSystemTreeView.tsx, dashboard/src/views/DetailPage/EntityDetailPage.tsx, dashboard/src/views/DetailPage/EntityDetailTabs/LineageTab.tsx, dashboard/src/views/Lineage/LineageLayout.tsx, dashboard/src/views/Lineage/atlas-lineage/LICENSE, dashboard/src/views/Lineage/atlas-lineage/package-lock.json, dashboard/src/views/Lineage/atlas-lineage/package.json, dashboard/src/views/Lineage/atlas-lineage/src/Enums.js, dashboard/src/views/Lineage/atlas-lineage/src/Utils/DataUtils.js, dashboard/src/views/Lineage/atlas-lineage/src/Utils/LineageUtils.js, dashboard/src/views/Lineage/atlas-lineage/src/Utils/index.js, dashboard/src/views/Lineage/atlas-lineage/src/index.js, dashboard/src/views/Lineage/atlas-lineage/src/styles/__varibale.scss, dashboard/src/views/Lineage/atlas-lineage/src/styles/graph.scss, dashboard/src/views/Lineage/atlas-lineage/src/styles/style.scss, dashboard/src/views/Lineage/atlas-lineage/webpack.config.js
ATLAS-5033 : Migrate Lineage Module from Backbone.js to React.
Manually tested with local build.
=> ATLAS-5033 : Migrate Lineage Module from Backbone.js to React.

dev-support/atlas-docker/docker-compose.atlas-hadoop.yml, dev-support/atlas-docker/docker-compose.atlas-hbase.yml, dev-support/atlas-docker/docker-compose.atlas-hive.yml, dev-support/atlas-docker/docker-compose.atlas.yml
added healthcheck and dependencies in HDFS, HBase, Hive and Atlas containers.
Verified that Atlas docker setup successfully completes startup.
=> ATLAS-5058: added healthcheck in docker setup

dashboard/src/views/DetailPage/EntityDetailTabs/PropertiesTab/BMAttributes.tsx, dashboard/src/views/DetailPage/EntityDetailTabs/PropertiesTab/Labels.tsx, dashboard/src/views/DetailPage/EntityDetailTabs/PropertiesTab/UserDefinedProperties.tsx
ATLAS-5077 & ATLAS-5076
Manual testing on local with some data and without data.
=> React UI: Save button should be disabled if API call is in progress for User-defined properties, Labels & BM attributes panel.

dashboard/src/views/SideBar/SideBarTree/EntitiesTree.tsx, dashboard/src/views/SideBar/SideBarTree/SideBarTree.tsx
[ATLAS-5079](https://issues.apache.org/jira/browse/ATLAS-5079)
Manually tested for all the components.
=> ATLAS-5079 : React UI: Mutiple clicks on refresh Buttons on Sidebar component triggers multiple API calls.

dashboard/src/views/DetailPage/EntityDetailTabs/ProfileTab.tsx
[ATLAS-5083](https://issues.apache.org/jira/browse/ATLAS-5083)
Manually tested.
=> ATLAS-5083 : (React UI)Wrong parameter is added in the API request body, when the entity detail page is refreshed after selecting Table tab.

addons/impala-bridge/src/test/java/org/apache/atlas/impala/ImpalaLineageToolTest.java, addons/impala-bridge/src/test/java/org/apache/atlas/impala/hook/AtlasImpalaHookContextTest.java, addons/impala-bridge/src/test/java/org/apache/atlas/impala/hook/ImpalaOperationParserTest.java, addons/impala-bridge/src/test/java/org/apache/atlas/impala/hook/events/BaseImpalaEventTest.java, addons/impala-bridge/src/test/java/org/apache/atlas/impala/hook/events/CreateImpalaProcessTest.java
junit coverage for module impala-bridge
tested with cmd ====> mvn clean verify
(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)
=> ATLAS-5069:Improve Unit Test Coverage for Impala-bridge Module

dashboard/src/App.tsx, dashboard/src/components/Table/TableLayout.tsx, dashboard/src/components/muiComponents.tsx, dashboard/src/styles/entityForm.scss, dashboard/src/styles/formFields.scss, dashboard/src/styles/table.scss, dashboard/src/views/DetailPage/EntityDetailTabs/PropertiesTab/Labels.tsx, dashboard/src/views/Entity/EntityForm.tsx, dashboard/src/views/Layout/About.tsx, dashboard/src/views/SideBar/SideBarBody.tsx, dashboard/src/views/SideBar/SideBarTree/SideBarTree.tsx, dashboard/src/views/Statistics/Statistics.tsx
[ATLAS-5087](https://issues.apache.org/jira/browse/ATLAS-5087)
1. Replaced all the Spinner loaders used inside the application with Skeleton loader.
2. Pagination doesn't appear while table data is loading.
3. Fixed the text area font globally.
4. Increase the speed of the main loader which appears when application.
=> ATLAS-5087 : React UI : Cosmetic changes and Improvements.

dashboard/src/components/Table/TableLayout.tsx, dashboard/src/components/Table/TablePagination.tsx, dashboard/src/components/commonComponents.tsx, dashboard/src/models/tableLayoutType.ts, dashboard/src/styles/table.scss, dashboard/src/utils/Enum.ts, dashboard/src/utils/Messages.ts, dashboard/src/utils/Utils.ts, dashboard/src/views/Administrator/Audits/AdminAuditTable.tsx, dashboard/src/views/DetailPage/EntityDetailTabs/AuditsTab.tsx, dashboard/src/views/DetailPage/EntityDetailTabs/ClassificationsTab.tsx, dashboard/src/views/DetailPage/EntityDetailTabs/ProfileTab.tsx, dashboard/src/views/DetailPage/EntityDetailTabs/ReplicationAuditTab.tsx, dashboard/src/views/SearchResult/RelationShipSearch.tsx, dashboard/src/views/SearchResult/SearchResult.tsx, dashboard/src/views/SideBar/SideBarTree/SideBarTree.tsx
[ATLAS-5036](https://issues.apache.org/jira/browse/ATLAS-5036)
The 'Go to Page' input resets after entering a number, and the displayed page number is incorrect. Also, font size and alignment for pagination controls (Go to, Next, Previous) are inconsistent.
Changes are implemented for the Search result page, Entity detail page - audit table, classification table, Admin audit.
Manual tested
=> ATLAS-5036: [React UI] Pagination Issue: 'Go to Page' input resets and Incorrect page number Display with font & alignment inconsistencies.

dashboard/src/utils/Enum.ts, dashboard/src/views/Administrator/Audits/AuditResults.tsx
Auto Purge audits to be displayed on admin audits for react ui
manually tested.
=> ATLAS-5138: React UI: Display Auto Purge

dashboard/src/components/Forms/FormTreeView.tsx, dashboard/src/views/DetailPage/DetailPageAttributes.tsx, dashboard/src/views/DetailPage/EntityDetailPage.tsx, dashboard/src/views/Glossary/AssignTerm.tsx
When attempting to assign a blank term to an entity, an error occurs.
=> ATLAS-5105: [REACT UI] Incorrect errors being displayed when assigning blank term to entity.

docs/package-lock.json, docs/package.json, repository/src/main/java/org/apache/atlas/repository/store/graph/v2/tasks/ClassificationTask.java
Upgrade axios version to 1.12.0
Manual testing
PC build: https://ci-builds.apache.org/job/Atlas/job/PreCommit-ATLAS-Build-Test/1988/
=> ATLAS-5136: Upgrade axios version to 1.12.0
