intg/src/main/java/org/apache/atlas/model/typedef/AtlasEntityDef.java
Implemented constructors in AtlasEntityDef to create types with servicetype attribute.
=> ATLAS-3096: Missing AtlasEntityDef constructors for serviceTpe

distro/src/conf/atlas-log4j.xml
Jira ticket: https://issues.apache.org/jira/browse/ATLAS-3293
=> ATLAS-3293: Move LARGE_MESSAGES log to correct directory

repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasTypeDefGraphStoreV2.java
new Date() is just a thin wrapper around System.currentTimeMillis(). Using System.currentTimeMillis() is better since we don't need create a new object and the system can speed up.
=> ATLAS-3134 Change Date.getTime() to System.currentTimeMillis() for better performance.

dev-support/atlas-docker/Dockerfile
Disabling package-lock.json Locally to avoid failure during build  "npm notice created a lockfile as package-lock.json. You should commit this file."
=> ATLAS-3567 - Bypass package-lock.json error during build

addons/models/1000-Hadoop/1100-spark_model.json
Create `spark_column_lineage` type and relationship definition to add support of column level lineage for `CREATE TABLE AS SELECT ...` statements and views. Column level lineage refers to lineage created between the input and output columns.
For example:
```
hive > create table employee_ctas as select id from employee;
```    
For the above query, lineage is created from `employee` to `employee_ctas`, and also from `employee.id` to `employee_ctas.id`.
Manually using modified version of Spark Atlas Connector:
- Installed and started Atlas.
- `1100-spark_model.json` is updated with proposed changes. Atlas is restarted.
- Executed the next statements using spark-shell:
```
spark.sql("create table sparkemployee_1_2(id int,name string)");
spark.sql("create table sparkemployee_ctas_1_2 as …
```
=> ATLAS-3661 Create 'spark_column_lineage' type and relationship definition

addons/models/1000-Hadoop/1100-spark_model.json
Create `spark_application` type to avoid `spark_process` from being updated for multiple operations. Currently, Spark Atlas Connector uses `spark_process` as a top-level type for a Spark session, thus it's being updated for multiple operations within the same session.
The following statements:
```
spark.sql("create table table_1(col1 int,col2 string)");
spark.sql("create table table_2 as select * from table_1");
```
result in the next correct lineage:
```
table1 ------> spark_process1 -------> table2
```
but executing similar statements in the same spark session:
```
spark.sql("create table table_3(col1 int,col2 string)"); 
spark.sql("create table table_4 as select * from table_3");
```
result in the same `spark_process` being updated and the lineage now connects all the 4 tables.
The …
=> ATLAS-3655: Create 'spark_application' type to avoid 'spark_process' from being updated for multiple operations

addons/models/1000-Hadoop/1100-spark_model.json
Create new `spark_ml_model_dataset` and `spark_ml_pipeline_dataset` relationship definitions. This is required in order to integrate Spark Atlas Connector's ML event processor.
Previously, Spark Atlas Connector used the `spark_ml_directory` model for the ML model directory and `spark_ml_model_ml_directory`, `spark_ml_pipeline_ml_directory` relationship definitions. Usage of the `spark_ml_directory`  was reverted in the scope of https://github.com/hortonworks-spark/spark-atlas-connector/issues/61, https://github.com/hortonworks-spark/spark-atlas-connector/pull/62 so ML model directory is `DataSet` entity(i.e. `hdfs_path`, `fs_path`).
Thus, new relationship definitions must be created, since there is no straightforward way to update existing ones to use `DataSet` type instead of it's child …
=> ATLAS-3646 Create new 'spark_ml_model_dataset','spark_ml_pipeline_dataset' relationship defs

addons/models/1000-Hadoop/patches/015-spark_process_add_query_text_attribute.json
Add `queryText` attribute to the `spark_process` type in order to make `spark_process` more readable by the user. The `queryText` attribute stores exact SQL query that is executed within Spark session as a `spark_process`.
Manually using modified version of Spark Atlas Connector:
- Install and start Atlas.
- Stop Atlas.
- Copy `015-spark_process_add_query_text_attribute.json` to `models/1000-Hadoop/patches`.
- Start Atlas.
- Verify that patch is applied and `application.log` contains the following entry:
```
INFO  - [main:] ~ TYPEDEF_PATCH_1000_015_001 (status: APPLIED; action: ADD_ATTRIBUTE) in file: ...
```
- Execute the next statements using spark-shell:
```
spark.sql("create table source_2_77_10(id int, new_id int, name string)");
spark.sql("create table ctas_2_77_10 as select id as …
```
=> ATLAS-3665 Add 'queryText' attribute to the 'spark_process' type

pom.xml
- Maven package `cassandra-all` has transitive dependency on `org.yaml:snakeyaml:1.11` which has CVE-2017-18640:https://nvd.nist.gov/vuln/detail/CVE-2017-18640
- Raised a PR to Cassandra to upgrade the version of `snakeyaml` to `1.26` where the CVE got fixed : https://github.com/apache/cassandra/pull/736
- Upgrade to the latest version once `cassandra-all` new release become available
=> ATLAS-3940 : Upgrade snakeyaml to a version without CVE-2017-18640

common/src/main/java/org/apache/atlas/utils/KafkaUtils.java, common/src/test/java/org/apache/atlas/utils/KafkaUtilsTest.java
Fix `KafkaUtils` to always enclose property values in double-quotes. This helps to avoid the following error with Spark Atlas Connector trying to configure Atlas client to use delegation tokens:
```
java.lang.IllegalArgumentException: Value not specified for key 'null' in JAAS config
at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:116)
at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63)
at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:90)
at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:84)
```
The following configuration is not handled properly:
```
atlas.jaas.KafkaClient.option.username=30CQ4q1hQMy0dB6X0eXfxQ
atlas.jaas.KafkaClient.option.password=KdaUQ4FlKWlDxwQrAeFGUVb …
```
=> ATLAS-4263: Fix KafkaUtils to always enclose property values in double-quotes

intg/src/main/python/apache_atlas/utils.py
Some of the python client api endpoints are currently broken as the result of the concatenation of the base url with the relative context path items.
Specifically this happens for those path which contain a trailing forward slash (`/`), e.g.
- https://github.com/apache/atlas/blob/master/intg/src/main/python/apache_atlas/client/entity.py#L61 and
- https://github.com/apache/atlas/blob/master/intg/src/main/python/apache_atlas/client/entity.py#L58
This produced requests of the kind:
```
/api/atlas/v2/entity/uniqueAttribute/type//topic_schema
```
which obviously resulted in errors.
Instead of simply removing the `/` from the base paths I've chosen the approach of replacing the url concatenation method with a more robust one that handles leading and trailing slashes transparently.
I did not …
=> ATLAS-4318 : fix python client api url concatenation

intg/src/main/python/apache_atlas/client/entity.py
Replacing the commas with colons so that the `query_params` is correctly created as dictonary instead of a set.
Related to https://github.com/apache/atlas/pull/129
=> ATLAS-4318 : Fixed bug in entity.py

webapp/src/main/java/org/apache/atlas/examples/QuickStartV2.java
With the present code, on running quick_start.py, locationUri is not flowing in for DB entities. This fix will help associate the locationUri tag to the DB entities.
=> ATLAS-4320 : Fixing location uri for DB entities in QuickStartV2

.gitignore
By modifying the `.gitignore` configuration file, we can ignore the files generated under `webapp/overlays` and avoid submitting temporary files by mistake.
=> ATLAS-4321 : Ignore files generated under webapp/overlays

distro/src/bin/atlas_config.py
This patch will remove a useless pass statement in `atlas_config.py` file.
=> ATLAS-4318 : Remove useless pass statement in python client

atlas-examples/sample-app/src/main/python/entity_example.py, distro/src/bin/atlas_admin.py, distro/src/bin/atlas_update_simple_auth_json.py, distro/src/bin/quick_start.py, distro/src/bin/quick_start_v1.py
This patch will remove these unnecessary imports from python scripts.
=> ATLAS-4318 : Remove unnecessary imports from python script

pom.xml
It comes with a newer RocksDB JNI that supports Linux ARM64
=> ATLAS-4159 Update Apache Storm to 2.3.0

pom.xml
fix CVE-2021-44228
https://logging.apache.org/log4j/2.x/security.html
=> ATLAS-4505: Update log4j2 version to 2.15.0

client/client-v2/src/main/java/org/apache/atlas/AtlasClientV2.java
`AtlasClientV2.addLabels` by unique attribute method and `AtlasClientV2.setLabels` by unique attribute method use incorrect `API_V2`.
=> ATLAS-4785: Fix incorrect references in AtlasClientV2 label methods

.asf.yaml
Current .asf.yaml notification settings for atlas.git can be viewed at: https://gitbox.apache.org/schemes.cgi?atlas.
The PR changes:
- settings, adds branch protection on master and fixes the labels
- autolink jira with every commit
- adds description and homepage
=> ATLAS-4982: Define description/topics/merge strategy for the github repository with .asf.yaml

.github/workflows/ci.yml
Enable atlas builds to run via GitHub Actions with Apache Infra.
=> ATLAS-4981: Enable CI for Apache Atlas via GitHub Actions

.github/workflows/ci.yml
Volume mounts are used during maven build, the CI job is run with `runner` user whereas the docker-build is run via `atlas` user.
The PR adds file permissions to enable correct permissions across volume mounts to the container.
latest CI run
=> ATLAS-4981: Add file permissions to resolve atlas build issues in docker 

pom.xml
Doesn't seem to be used. This version is very out of date if it is - especially since Akka now has a Category X license.
=> [MINOR] remove akka.version in pom.xml

repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasBusinessMetadataDefStoreV2.java, repository/src/test/java/org/apache/atlas/repository/store/graph/v2/AtlasBusinessMetadataDefStoreV2Test.java
Fix for : If businessMetadata is created without adding any applicable types (Assigned Entity types), NullPointerException is thrown when we try to delete that particular businessmetadata.
Unit test case is added for the same.
=> ATLAS-4863: NPE while deleting BusinessMetadata

.github/workflows/ci.yml
If the maven build inside the container `atlas-build` fails, it should cause CI to fail immediately and subsequent steps shouldn't be run.
CI
=> ATLAS-4981: Interrupt CI if maven build inside the container fails

dev-support/atlas-docker/README.md
ATLAS-4993: Ensure ${HOME}/.m2 directory exists before starting Atlas build
Updated the README to ensure the `${HOME}/.m2` directory exists before starting the Atlas build process.
Instead of adding a separate step, Step **6.1** now includes:
mkdir -p ${HOME}/.m2
before starting the build.  
This prevents permission errors without requiring a full recursive `chown`, which could slow down the process.
- Manually verified that:
- The `${HOME}/.m2` directory is created if missing.
- The Atlas build process runs without `.m2` directory-related permission issues.
- The fix does not introduce significant delays in the build process.
=> ATLAS-4993: Ensure ${HOME}/.m2 directory exists before starting Atlas build

webapp/src/main/java/org/apache/atlas/web/filters/AtlasAuthenticationFilter.java, webapp/src/main/java/org/apache/atlas/web/filters/AtlasCSRFPreventionFilter.java, webapp/src/main/java/org/apache/atlas/web/filters/AtlasKnoxSSOAuthenticationFilter.java, webapp/src/main/java/org/apache/atlas/web/filters/HeadersUtil.java, webapp/src/main/java/org/apache/atlas/web/servlets/AtlasHttpServlet.java, webapp/src/test/java/org/apache/atlas/web/filters/HeaderUtilsTest.java
We have added the header while login.jsp page. header can be set at properties file or static header.
Pre-commit link :- https://ci-builds.apache.org/job/Atlas/job/PreCommit-ATLAS-Build-Test/1824/console 
manull testing, unit test-case added.
=> ATLAS-5019 : Add header in atlas login.jsp page

repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
ATLAS-5024:  Improve fetching edges of the vertex
Extending [ATLAS-4803](https://reviews.apache.org/r/74713/bugs/ATLAS-4803/)
Relationship attributes, classifications of a particular entity(vertex) as vertices which is linked with an edge.
Hence while performing classifications/relationship, edges are fetched.
AtlasVertex.hasEdges() checks whether a particular vertex has any edges.
This method is used in some cases, followed by getting the edges of that vertex through query.
Action:
If there are many edges of a particular vertex, time spent on checking hasEdge can also take much time. hence it can be removed
Tests Planned:
1. PC Build successful:[Link]( https://ci-builds.apache.org/job/Atlas/job/PreCommit-ATLAS-Build-Test/1855/)
2. Manual tests
3. Functional tests
=> ATLAS-5024: Improve fetching edges of the vertex

repository/src/main/java/org/apache/atlas/repository/graph/FullTextMapperV2.java, repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
Log level of couple of statements changed from INFO to DEBUG, to reduce noise in the log file in production environment.
Verified that the messages don't appear in Atlas server log file.
=> ATLAS-5035: reduce info level logs during classification updates

pom.xml, webapp/pom.xml
Upgraded Spring ldap core version to 2.4.4
Tested by creating tables through all Hooks
Did sanity testing for Classification ,labels,BMs and CURL calls
Atlas server running successfully
PC is successful
=> ATLAS-5057: Atlas - Upgrade spring-ldap-core to 2.4.4/3.2.8

intg/src/main/java/org/apache/atlas/security/SecurityProperties.java, webapp/src/main/java/org/apache/atlas/notification/ImportTaskListenerImpl.java, webapp/src/main/java/org/apache/atlas/web/service/SecureEmbeddedServer.java, webapp/src/test/java/org/apache/atlas/notification/ImportTaskListenerImplTest.java
The new asynchronous import feature had to start all of the import in backend which made the app startup longer, this PR fixes the same by making the import start up asynchronous thus not blocking the class initialization and app start up to wait. 
Manual testing by patching to cluster and Unit test
=> ATLAS-5061: Fix slow startup by making the import startup asynchronous

.github/workflows/ci.yml, dev-support/atlas-docker/Dockerfile.atlas-build, dev-support/atlas-docker/docker-compose.atlas-build.yml, dev-support/atlas-docker/scripts/atlas-build.sh, dev-support/checks/coverage.sh, pom.xml
Integrate code coverage with JaCoCo in CI
- Introduce Maven JaCoCo plugin
- Merge all `jacoco.exec` files generated as part of JDK8 build into a single `.exec` file.
- Run report generation and upload artifacts for consumption
Tested the changes in local docker build
=> ATLAS-5054: Introduce JaCoCo plugin and generate Code Coverage results with CI

.github/workflows/ci.yml, dev-support/atlas-docker/docker-compose.atlas-hadoop.yml, dev-support/atlas-docker/docker-compose.atlas-hive.yml
Since health checks for respective containers are in place, `ci.yml` can be updated to rely on this.
CI: https://github.com/kumaab/atlas/actions/runs/16156151540/job/45598946514
=> ATLAS-5058: Update ci.yml to rely on healthchecks

webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java, webapp/src/test/java/org/apache/atlas/web/integration/BasicSearchIT.java, webapp/src/test/resources/json/search-parameters/attribute-filters.json, webapp/src/test/resources/json/search-parameters/attribute-name.json, webapp/src/test/resources/json/search-parameters/attribute-value.json, webapp/src/test/resources/json/search-parameters/operator.json, webapp/src/test/resources/json/search-parameters/tag-filters.json
- Initially under basic and classification search, only basic [Add filter] option on UI,  validation was done. Also, for [Add Group FIlter]option on UI  it was throwing exception and errors.
- So in this PR we have fixed that issue and we have handled filter search validation for both basic and complex filter groups.
- Group FIlter - it recursively calls Filter SearchParameters. eg: In FilterCriteria class we have List<FilterCriteria> criterion, so entityFilters attribute in SearchParametrs class recursively calls criterion in itself multiple times.
- Apart have added TC to test negative scenarios for quick search and basic search
Conclusion:
"entityFilters": {
>     "condition": "AND",
>     "criterion": [
>       {
>         "attributeName": "__classificationNames",
> …
=> ATLAS-5053: Add recursive validation in Basic Search API to fix regression issue

dashboard/src/api/apiUrlLinks/commonApiUrl.ts
When the Apache Atlas service is up using KNOX, on React UI, all the API's are giving 404 error (no network connected).
Solution:
API path doesn't contain the full path with KNOX. By adding the full URL in the API, including the Knox part, this will fix the issue.
Tested Manually.
=> ATLAS-5081: React UI all API's are failing when accessing through KNOX.

authorization/src/main/java/org/apache/atlas/authorize/AtlasAccessRequest.java, authorization/src/test/java/org/apache/atlas/authorize/simple/AtlasSimpleAuthorizerTest.java, repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
1.Refactored code to reduce the time taken for processing classification updates for large numbers of entities.
2.Optimized internal method calls to avoid redundant operations.
1.This patch was tested by measuring the time taken by the bulk/classification API to handle 260 items, both before and after the code changes.
2.The test was done using different numbers of classifications (3, 5, 10, and 20). The results were averaged over three runs to ensure accuracy.
Results after code changes:
Classifications	Entities	Time Taken (seconds)
20	                260	          93.48
10	                260	          39.33
5	                260	          25.55
3	                260	          18.07
Results before code changes:
Classifications	Entities	Time Taken (seconds)
20	                  260 …
=> ATLAS-4916 : Improve Efficiency in Access Request Handling by Optimizing Classification Retrieval

addons/kafka-bridge/src/test/java/org/apache/atlas/kafka/bridge/KafkaBridgeTest.java, addons/kafka-bridge/src/test/java/org/apache/atlas/kafka/bridge/SchemaRegistryConnectorTest.java
Added junits for kafka-bridge module
tested using cmd =====> mvn clean verify
=> ATLAS-5090:Improve Unit Test Coverage for Kafka-bridge Module

addons/hive-bridge/pom.xml, addons/hive-bridge/src/test/java/org/apache/atlas/hive/bridge/HiveMetaStoreBridgeTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/AlterDatabaseTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/AlterTableRenameColTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/AlterTableRenameTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/AlterTableTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/BaseHiveEventTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/CreateDatabaseTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/CreateHiveProcessTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/CreateTableTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/DropDatabaseTest.java, addons/hive-bridge/src/test/java/org/apache/atlas/hive/hook/events/DropTableTest.java
Added Unit TCs for Hive module
- CI Build
- PC Build: https://ci-builds.apache.org/job/Atlas/job/PreCommit-ATLAS-Build-Test/1966/
- mvn clean install and verify build locally (both success)
- docker run locally
=> ATLAS-5068: Improve Unit Test Coverage for Hive-bridge Module

dashboard/src/components/Table/TableLayout.tsx, dashboard/src/styles/table.scss
ATLAS-5051: [React UI] Fix expand row icon width issue in table body
manual tested
=> ATLAS-5051: [React UI] Fix expand row icon width issue in table body

dashboardv2/gruntfile.js, dashboardv2/package-lock.json, dashboardv2/package.json, dashboardv3/gruntfile.js, dashboardv3/package-lock.json, dashboardv3/package.json
Since node-sass is deprecated, it may cause build failures in the future. To avoid this, please replace node-sass with the sass package.
=> ATLAS-5137: Atlas UI: Replace Node-Sass with Sass library.

dashboard/src/views/SearchResult/SearchResult.tsx
If the entity is empty, the message "No Records Found!" will be displayed.
Manually tested.
=> ATLAS-5110: [REACT UI] Incorrect entities are being displayed for Empty entity types

dashboard/src/components/Table/TableLayout.tsx, dashboard/src/components/muiComponents.tsx, dashboard/src/views/SearchResult/SearchResult.tsx, dashboardv2/public/js/views/graph/LineageLayoutView.js, dashboardv2/public/js/views/graph/TypeSystemTreeView.js, dashboardv3/public/js/views/graph/LineageLayoutView.js, dashboardv3/public/js/views/graph/TypeSystemTreeView.js
Precondition: Data from quick_start.py should be present.
These DSL queries do not display data as expected:
Table select min(createTime)
Table groupby(owner)
Table groupby(createTime) select owner, name, max(createTime)
Table groupby(createTime) select owner, name, min(createTime)
Table groupby(owner) select owner, count()
hive_db select __timestamp, __modificationTimestamp, __state, __createdBy
The search results pages do not display aggregated information nor the columns stated in the queries.
manually tested
=> ATLAS-5132: [REACT UI] Unique Advanced/Search queries do not work as expected

dashboard/src/components/ImportDialog.tsx
Importing Business metadata UI is calling Import Glossary functionality and data never gets imported in Atlas entity, but instead a glossary gets created. On repeating the import again it throws an error.
=> ATLAS-5131:[REACT UI] Glossary import being used instead of business metadata import.

graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusIndexQuery.java
Example: When performing a search of entities i particular typedef let's say: "hdfs_path",  if the number of entities exceeds the default pagination limit (25), the approximateCount field in the AtlasSearchResult incorrectly reports only 25, even when more entities exist.
Also, if we decrease the pagination limit to any random number lets say 5, the approximate count will be shown as 5
Before the Fix:
Create 26 entities of a type.
Perform a search using the API without explicitly setting limit and offset (defaults to 25).
Observe that approximateCount is reported as 25 instead of 26
After the Fix
approximateCount value is reported as totalEntityCount present in particular typedefinition
Fix Done:
updating vertexTotals() in  AtlasIndexJanusQuery Class, that returns:     return …
=> ATLAS-5147: Search API approximateCount value shows pageLimit value instead of total entity count

dashboard/src/components/Table/TableLayout.tsx, dashboard/src/styles/table.scss
Currently, the table headers in the Search and Business Metadata sections appear visually constrained or misaligned when there are zero records. This impacts the layout consistency and user experience.
=> ATLAS-5151:React UI: Fix UI layout issue for tables when no records are present.
